name: "elastic_example"
backend: “pytorch"
max_batch_size: 0

input [
  {
    name: "input_0"
    data_type: TYPE_FP32
    dims: [ 1, 5 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
